---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo1
  name: tdemo1
spec:
  env:
  - name: "foo"
    value: "bar"
  build: 
    env: 
    - name: BP_JVM_VERSION
      value: "17  
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1
