apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdemo1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo1
  
spec:
  env:
    - name: message
      value: tanzu
  source:
    git:
      url: https://github.com/tfynes-pivotal/tdemo1
      ref:
        branch: main
